version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  front:
    build: ./front
    ports:
      - "3000:3000"
  back:
    build: ./back
    ports:
      - "8000:8000"
    depends_on:
      - db